name: Main CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  main:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
      if: matrix.os == 'windows-latest'
    - name: Build
      if: matrix.os != 'windows-latest'
      run: make
    - name: Build (Windows)
      if: matrix.os == 'windows-latest'
      run: nmake -nologo
    - name: Test
      shell: bash
      run: |
        set -euo pipefail
        err=0
        ./simd-integration 2>&1 | tee output.log || err=$?
        echo "::group::Publish logs"
        content=$(cat output.log)
        content=${content//'%'/'%25'}
        content=${content//$'\n'/'%0A'}
        content=${content//$'\r'/'%0D'}
        if [ $err = 0 ]; then
            echo "::notice file=output.log::${content}"
        else
            echo "::error file=output.log::${content}"
        fi
        echo "::endgroup::"
        exit $err
