name: Main CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  main:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
      if: matrix.os == 'windows-latest'
    - name: Build
      if: matrix.os != 'windows-latest'
      run: make
    - name: Build (Windows)
      if: matrix.os == 'windows-latest'
      run: nmake -nologo
    - name: Test
      run: ./simd-integration
